version: '3'

vars:
  MODULES: inventory order payment
  GCI_PREFIX: github.com/xgmsx/rsf

  # версии утилит
  GO_VERSION: '1.24'
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.8.0'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  MERGE_OPENAPI_VERSION: 'v1.0.0'
  GRPCURL_VERSION: 'v1.9.3'
  OGEN_VERSION: 'v1.12.0'
  YQ_VERSION: 'v4.45.2'

  # версии protoc-плагинов
  PROTOC_VERSION: '31.1'
  PROTOC_GEN_GO_VERSION: 'v1.36.6'
  PROTOC_GEN_GO_GRPC_VERSION: 'v1.5.1'
  PROTOC_GEN_GRPC_GATEWAY_VERSION: 'v2.26.3'
  PROTOC_GEN_OPENAPIV2_VERSION: 'v2.26.3'
  PROTOC_GEN_VALIDATE_VERSION: 'v1.2.1'

  # версии proto-зависимостей
  PROTO_GOOGLEAPIS_VERSION: 'e4686281e5e83657e579b835994a132d34f7e49e'
  PROTO_GEN_VALIDATE_VERSION: 'v1.2.1'

  # пути к исполняемым файлам
  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  MERGE_OPENAPI: '{{.BIN_DIR}}/go-merge-openapi'
  GRPCURL: '{{.BIN_DIR}}/grpcurl'
  OGEN: '{{.BIN_DIR}}/ogen'
  YQ: '{{.BIN_DIR}}/yq'

  PROTOC: '{{.BIN_DIR}}/protoc/bin/protoc'
  PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
  PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'
  PROTOC_GEN_GRPC_GATEWAY: '{{.BIN_DIR}}/protoc-gen-grpc-gateway'
  PROTOC_GEN_OPENAPIV2: '{{.BIN_DIR}}/protoc-gen-openapiv2'
  PROTOC_GEN_VALIDATE: '{{.BIN_DIR}}/protoc-gen-validate'

  PROTO_GOOGLEAPIS_DIR: '{{.BIN_DIR}}/proto-libs/googleapis'
  PROTO_GEN_VALIDATE_DIR: '{{.BIN_DIR}}/proto-libs/gen_validate'

tasks:

  update:deps:
    desc: "Обновление зависимостей в go.mod во всех модулях"
    cmds:
      - |
        echo "🔄 Обновление зависимостей в go.mod во всех модулях"
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🔄 Обновление зависимостей в $mod"
            (cd "$mod" && go mod tidy -compat=1.24) || exit 1
          fi
        done

  lint:
    desc: "Запускает golangci-lint для всех модулей"
    deps: [ install:golangci-lint ]
    cmds:
      - |
        set -e
        ERR=0
        echo "🔍 Проверяем модули..."
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🔍 Проверяем модуль $mod"
            {{.GOLANGCI_LINT}} run $mod/... --config=.golangci.yml || ERR=1
          fi
        done
        exit $ERR

  lint:proto:
    deps: [ install:protoc, install:protoc-plugins, install:proto-deps ]
    desc: "Проверка .proto-файлов проекта"
    cmds:
      - |
        echo "🔍 Проверяем proto файлы..."
        for mod in {{.MODULES}}; do
          if [ -d "$mod/proto" ]; then
            find "$mod/proto" -name "*.proto"  | while read -r file; do
              echo "🔍 Проверяем proto файл $file..."
              {{.PROTOC}} \
                --proto_path="$mod/proto" \
                --proto_path='{{.PROTO_GOOGLEAPIS_DIR}}' \
                --proto_path='{{.PROTO_GEN_VALIDATE_DIR}}' \
                --descriptor_set_out=/dev/null \
                "$file" || exit 1  
            done
          fi
        done

  format:
    desc: "Форматирует весь проект gofumpt + gci, исключая mocks"
    deps: [ install:formatters ]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt..."
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🧼 Форматируем $mod"
            find $mod -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT}} -extra -w {} +
          fi
        done
      - |
        echo "🎯 Сортируем импорты через gci..."
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🎯 Сортируем импорты в $mod"
            find $mod -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI}} write -s standard -s default -s "prefix({{.GCI_PREFIX}})" {} +
          fi
        done

  gen:
    desc: "Генерация всех proto и OpenAPI деклараций"
    cmds:
      - task: gen:openapi
      - task: gen:proto

  gen:openapi:
    desc: "Генерация Go-кода из всех OpenAPI-деклараций с x-ogen"
    deps: [ install:ogen, install:yq ]
    cmds:
      - |
        for mod in {{.MODULES}}; do
          if [ -d "$mod/api" ]; then
            find "$mod/api" -name '*openapi.yaml' -o -name '*openapi.yml' | while read -r file; do
              if [ -f "$file" ] && grep -q 'x-ogen:' "$file"; then
                target_api_dir="./shared/api"
                target_openapi_dir="./shared/pkg/openapi/$mod"
                mkdir -p $target_api_dir && mkdir -p $target_openapi_dir
                target=$target_openapi_dir/$({{.YQ}} e '."x-ogen".target' "$file")
                package=$({{.YQ}} e '."x-ogen".package' "$file")
                echo "🚀 Generating from: $file"
                echo "📁 Target: $target_openapi_dir"
                {{.OGEN}} \
                  --target "$target" \
                  --package "$package" \
                  --clean \
                  "$file" || exit 1
                echo "🚀 Merging: $file"
                {{.MERGE_OPENAPI}} -config $file -output $target_api_dir/$package.swagger.json
              fi
            done
          fi
        done

  gen:proto:
    deps: [ lint:proto ]
    desc: "Генерация Go-кода из всех .proto файлов"
    cmds:
      - |
        for mod in {{.MODULES}}; do
          if [ -d "$mod/proto" ]; then
            find "$mod/proto" -name '*.proto' | while read -r file; do
              target_api_dir="./shared/api"
              target_proto_dir="./shared/pkg/proto/$mod"
              mkdir -p $target_api_dir && mkdir -p $target_proto_dir
              echo "🚀 Generating from: $file"
              echo "📁 Target: $target_proto_dir"
              {{.PROTOC}} \
                --proto_path="$mod/proto" \
                --proto_path='{{.PROTO_GOOGLEAPIS_DIR}}' \
                --proto_path='{{.PROTO_GEN_VALIDATE_DIR}}' \
                --plugin=protoc-gen-go={{.PROTOC_GEN_GO}} \
                --plugin=protoc-gen-go-grpc={{.PROTOC_GEN_GO_GRPC}} \
                --plugin=protoc-gen-grpc-gateway={{.PROTOC_GEN_GRPC_GATEWAY}} \
                --plugin=protoc-gen-validate={{.PROTOC_GEN_VALIDATE}} \
                --plugin=protoc-gen-openapiv2={{.PROTOC_GEN_OPENAPIV2}} \
                --go_out="$target_proto_dir" \
                --go_opt=paths=source_relative \
                --go-grpc_out="$target_proto_dir" \
                --go-grpc_opt=paths=source_relative \
                --grpc-gateway_out="$target_proto_dir" \
                --grpc-gateway_opt=paths=source_relative \
                --validate_out="lang=go,paths=source_relative:$target_proto_dir" \
                --openapiv2_out="$target_api_dir" \
                --openapiv2_opt=json_names_for_fields=false,allow_merge=true,merge_file_name=$mod \
                "$file" || exit 1
            done
          fi
        done
        
  install:protoc:
    desc: "Устанавливает protoc в каталог bin"
    cmds:
      - |
        [ -f {{.BIN_DIR}}/protoc/bin/protoc ] || {
          echo '📦 Downloading protoc...'
          mkdir -p {{.BIN_DIR}}/protoc
          curl -sSL \
            "https://github.com/protocolbuffers/protobuf/releases/download/v{{.PROTOC_VERSION}}/protoc-{{.PROTOC_VERSION}}-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m).zip" \
            -o {{.BIN_DIR}}/protoc/protoc.zip
          unzip -q {{.BIN_DIR}}/protoc/protoc.zip -d {{.BIN_DIR}}/protoc
          chmod +x {{.PROTOC}}
        }

  install:protoc-plugins:
    desc: "Устанавливает плагины protoc в каталог bin"
    cmds:
      - |
        [ -f {{.PROTOC_GEN_GO}} ] || {
          echo '📦 Installing protoc-gen-go...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/protobuf/cmd/protoc-gen-go@{{.PROTOC_GEN_GO_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GO_GRPC}} ] || {
          echo '📦 Installing plugin protoc-gen-go-grpc...'
          GOBIN={{.BIN_DIR}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@{{.PROTOC_GEN_GO_GRPC_VERSION}}
        }
        [ -f {{.PROTOC_GEN_GRPC_GATEWAY}} ] || {
          echo '📦 Installing plugin protoc-gen-grpc-gateway...'
          GOBIN={{.BIN_DIR}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@{{.PROTOC_GEN_GRPC_GATEWAY_VERSION}}
        }
        [ -f {{.PROTOC_GEN_VALIDATE}} ] || {
          echo '📦 Installing plugin protoc-gen-validate...'
          GOBIN={{.BIN_DIR}} go install github.com/envoyproxy/protoc-gen-validate@{{.PROTOC_GEN_VALIDATE_VERSION}}
        }
        [ -f {{.PROTOC_GEN_OPENAPIV2}} ] || {
          echo '📦 Installing plugin protoc-gen-openapiv2...'
          GOBIN={{.BIN_DIR}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@{{.PROTOC_GEN_OPENAPIV2_VERSION}}
        }

  install:proto-deps:
    desc: "Устанавливает зависимости googleapis и protoc-gen-validate"
    cmds:
      - |
        # Скачиваем googleapis
        [ -d {{.PROTO_GOOGLEAPIS_DIR}} ] || {
          echo '📦 Downloading googleapis...'
          mkdir -p {{.PROTO_GOOGLEAPIS_DIR}}
          curl -sSL https://github.com/googleapis/googleapis/archive/{{.PROTO_GOOGLEAPIS_VERSION}}.tar.gz | \
            tar -xz -C {{.PROTO_GOOGLEAPIS_DIR}} --strip-components=1
        }
        # Скачиваем protoc-gen-validate proto файлы
        [ -d {{.PROTO_GEN_VALIDATE_DIR}} ] || {
          echo '📦 Downloading protoc-gen-validate protos...'
          mkdir -p {{.PROTO_GEN_VALIDATE_DIR}}
          curl -sSL https://github.com/bufbuild/protoc-gen-validate/archive/refs/tags/{{.PROTO_GEN_VALIDATE_VERSION}}.tar.gz | \
            tar -xz -C {{.PROTO_GEN_VALIDATE_DIR}} --strip-components=1
        }

  install:ogen:
    desc: "Скачивает ogen в папку bin"
    cmds:
      - |
        [ -f {{.OGEN}} ] || {
          echo '📦 Устанавливаем ogen...'
          GOBIN={{.BIN_DIR}} go install github.com/ogen-go/ogen/cmd/ogen@{{.OGEN_VERSION}}
        }
        [ -f {{.MERGE_OPENAPI}} ] || {
          echo '📦 Устанавливаем go-merge-openapi...'
          GOBIN={{.BIN_DIR}} go install github.com/xgmsx/go-merge-openapi@{{.MERGE_OPENAPI_VERSION}}
        }

  install:yq:
    desc: "Устанавливает yq в каталог bin"
    cmds:
      - |
        [ -f {{.YQ}} ] || {
          echo '📦 Устанавливаем yq...'
          GOBIN={{.BIN_DIR}} go install github.com/mikefarah/yq/v4@{{.YQ_VERSION}}
        }

  install:formatters:
    desc: "Устанавливает форматеры gci и gofumpt в каталог bin"
    summary: |
      Эта задача проверяет наличие инструментов форматирования кода gofumpt и gci в директории bin.
      Если инструменты не найдены, они будут автоматически установлены с указанными версиями.
      
      Используется:
        - gofumpt: для форматирования кода Go
        - gci: для сортировки импортов Go
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  install:golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    summary: |
      Проверяет наличие golangci-lint в директории bin.
      Если инструмент не найден, автоматически устанавливает его через go install.
      
      Устанавливаемая версия: {{.GOLANGCI_LINT_VERSION}}
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  install:grpcurl:
    desc: "Устанавливает grpcurl в каталог bin"
    cmds:
      - |
        [ -f {{.GRPCURL}} ] || {
          echo '📦 Устанавливаем grpcurl {{.GRPCURL_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/fullstorydev/grpcurl/cmd/grpcurl@{{.GRPCURL_VERSION}}
        }
    status:
      - test -x {{.GRPCURL}}
