// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/xgmsx/rsf/payment/internal/model"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

type PaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentService) EXPECT() *PaymentService_Expecter {
	return &PaymentService_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, input
func (_m *PaymentService) PayOrder(ctx context.Context, input model.PayOrderInput) (model.PayOrderOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 model.PayOrderOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PayOrderInput) (model.PayOrderOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PayOrderInput) model.PayOrderOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(model.PayOrderOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PayOrderInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.PayOrderInput
func (_e *PaymentService_Expecter) PayOrder(ctx interface{}, input interface{}) *PaymentService_PayOrder_Call {
	return &PaymentService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, input)}
}

func (_c *PaymentService_PayOrder_Call) Run(run func(ctx context.Context, input model.PayOrderInput)) *PaymentService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PayOrderInput))
	})
	return _c
}

func (_c *PaymentService_PayOrder_Call) Return(_a0 model.PayOrderOutput, _a1 error) *PaymentService_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentService_PayOrder_Call) RunAndReturn(run func(context.Context, model.PayOrderInput) (model.PayOrderOutput, error)) *PaymentService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
